### ISSUE TITLE
turbolinks problem

### ISSUE THREAD

**Issue by mcmegavolt** [ai/fotoramajs#10]
Есть проблемка с турболинками, чтобы ее решить нужно что-то вроде:

```coffee
ready = ->
  ИНИЦИАЛИЗАЦИЯ

$(document).ready(ready)
$(document).on('page:load', ready)
```

Может сделать встроенную поддержку турболинков, чтобы не париться с этим? Или как?

Спасибо )

**Comment by ai** [comment]
Это тебе надо в главный репозиторий [fotorama](https://github.com/artpolikarpov/fotorama/) писать — тут только сборка для Rails.

Но там вряд ли кто-то сделает. Турболинки — мёртворождённый проект из-за того, что все библиотеки надо патчить.

Может быть [jquery.turbolinks](https://github.com/kossnocorp/jquery.turbolinks) решит проблему.

**Comment by mcmegavolt** [comment]
Спасибо, ну это не такая уж большая проблема, просто каждый раз это делать подкумаривает )
