### ISSUE TITLE
fotorama in Joomla - PlugIn ?

### ISSUE THREAD

**Issue by Krabtus** [ai/fotoramajs#11]
Hello, there is a possibility fotorama in the current Joomla version. With a plug-in? And is it with fotorama possible to access in HTML files on a complete folder, where then simply all the photos in it photos are presented as a gallery?

Class would be it if you could as with Sigplus over a simple code like {gallery} FOLDER {/gallery} on a complete folder could access.

As described e.g. These plugins allow ...
SIGE - Simple Image Gallery Extended
sigplus

**Comment by ai** [comment]
It is Fotorama pack for Ruby on Rails. Main Fotorama repo is https://github.com/artpolikarpov/fotorama/
